version: '3.8'

services:

#> server php
  php: 
    image: php:8.3-apache
    container_name: php8.3
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
    
    build:
      context: .
      dockerfile: Dockerfile
#< server php

#> database
  database:
    image: mysql:latest

    container_name: mysql8

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: ronan
      MYSQL_PASSWORD : root

    ports:
      - 3307:3306
#< database

#>PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8081:80
#> PhpMyAdmin